### ISSUE TITLE
Permmission problem

### ISSUE THREAD

**Issue by jianqiao-ms** [DDoSolitary/LxRunOffline#113] opened 2020-02-05 10:34 UTC
I have got a permmission problem when I install WSL distributions using LxRunOffline.
![image](https://user-images.githubusercontent.com/8119807/73834528-d8c63380-4846-11ea-8405-f2c65f78819a.png)

I have installed another distribution using [CentWSL](https://github.com/yuk7/CentWSL). And it's working correctly.

The LxRunOffline is installed by chocolatey.

**Comment by DDoSolitary** [comment] 2020-02-09 09:34
I tried the image provided with CentWSL and save by Docker and both of them are working well. What is the image file you're using (centos-7-docker.tar.xz)?

**Comment by jianqiao-ms** [comment] 2020-02-09 17:28
The image file I used is download from 
https://github.com/CentOS/sig-cloud-instance-images/raw/CentOS-7/docker/centos-7-docker.tar.xz
And the powershell is running with administrator.
I even tried Microsoft official WSL package, install it using LxRunOffice and the problem not solved.

Is there anything special I didn't noticed? Will you please check my procedure shown in the image? Thank you very much.

**Comment by DDoSolitary** [comment] 2020-02-10 12:08
![图片](https://user-images.githubusercontent.com/25856103/74148642-e57cca00-4c40-11ea-9887-73aabc5a90a0.png)

Unfortunately, I'm unable to reproduce the error you're experiencing.

Could you please provide which version of LxRunOffline you're running? Thanks.

**Comment by jianqiao-ms** [comment] 2020-02-10 22:58
![image](https://user-images.githubusercontent.com/8119807/74198104-a9c31e00-4c9b-11ea-9671-d25576eb00c8.png)
It's version 3.4.1

**Comment by DDoSolitary** [comment] 2020-06-18 05:37
I have to close this issue because I'm unable to reproduce it. Leave a comment if you find some new information that may help debugging.

**Closed by DDoSolitary** 2020-06-18 05:37 UTC
