### ISSUE TITLE
I don't see any linux terminal to work with when I run "LxRunOffline.exe run -w -n "focal""

### ISSUE THREAD

**Issue by Marietto2008** [DDoSolitary/LxRunOffline#121] opened 2020-05-02 13:47 UTC
Hello, sorry to be a dumbo, but how do I run the installed distribution ? I installed another Ubuntu distro using this command :

@echo off
lxrunoffline i -n focal -d C:\Users\marietto2020\Desktop\WSL\WSL\lxrunoffline\LxRunOffline-v3.4.1-msvc -f C:\Users\marietto2020\Desktop\WSL\WSL\lxrunoffline\ubuntu-focal-core-cloudimg-amd64-root.tar.gz -s
pause

it creates a short link to run the distro,that sounds like this :

LxRunOffline.exe run -w -n "focal"

well,when I run it,I see that it says "running",but I don't see any linux terminal to work with. These are the distros that I have installed on my system :

λ wsl -l -v
  NAME            STATE           VERSION
* focal           Stopped         2
  Ubuntu          Stopped         2
  Ubuntu-18.04    Stopped         2
  Ubuntu-20.04    Stopped         2
  Ubuntu-16.04    Stopped         1

I tried also to run focal with "wsl",but again,nothing happened. Or better : when I give another "wsl-l -v",I see something like this :

λ wsl -l -v
  NAME            STATE           VERSION
* focal           Running         2
  Ubuntu          Stopped         2
  Ubuntu-18.04    Stopped         2
  Ubuntu-20.04    Stopped         2
  Ubuntu-16.04    Stopped         1

it says that it is running,but where ?  I don't see any linux terminal where to put the commands. thanks.

![2020-05-02_13-48-17](https://user-images.githubusercontent.com/755339/80865902-6372cf00-8c8c-11ea-8cc3-b570bd06590d.png)

**Comment by DDoSolitary** [comment] 2020-05-02 14:13
I'm unable to reproduce this. Ubuntu focal works without issues on my local machine.

**Comment by DDoSolitary** [comment] 2020-05-02 14:14
Sorry, I clicked the close button by accident

**Comment by DDoSolitary** [comment] 2020-05-02 14:22
Does it work to run other distros installed from Store using LxRunOffline? And dose it work to run "focal" using the `wsl` command?

Though I'm not sure if it's relevant, it seems that you're using a third-party terminal emulator. Could you please tell me which one you're using so that I can check if it's related.

**Comment by Marietto2008** [comment] 2020-05-02 14:33
yes,the distros that I've installed from the ms store are working. Check the video that I have attached.

https://drive.google.com/open?id=1LTfEqiib3XbfHCShAJBJ7h5KV5d7i7xV

**Comment by DDoSolitary** [comment] 2020-05-04 14:56
Still unable to reproduce...

**Comment by DDoSolitary** [comment] 2020-06-18 05:38
I have to close this issue because I'm unable to reproduce it. Leave a comment if you find some new information that may help debugging.

**Closed by DDoSolitary** 2020-06-18 05:38 UTC
