### ISSUE TITLE
Is there any limit for the archive tar.gz distro?

### ISSUE THREAD

**Issue by Trophime** [DDoSolitary/LxRunOffline#37] opened 2018-03-26 13:09 UTC
Hi,
I'm trying to create a LXC container from my docker image.
I'm getting some errors. The archive is not completely unzipped and untarred.
It seems that the archive tar.gz file is big more than 1.8 G. 

Is there any limit for the archive tar.gz distro?
Best

**Comment by Biswa96** [comment] 2018-03-26 18:15
No there is no limit. WSL just need a working bash or sh binary in `/bin`. But the .tar.gz file should be properly compressed with `tar -czf` command.

**Comment by DDoSolitary** [comment] 2018-04-06 08:00
Closing as no response.

**Comment by Trophime** [comment] 2018-04-06 08:56
Sorry for not answering earlier, here are the steps to reproduce the problem:
On  a Linux Debian/Testing:
```
docker export $(docker create trophime/salome-8.4.0:nvidia) --ouptu="salome.tar"
gzip salome.tar
```
Then I copy the gzipped tarball on my Windows 10:
```
LXRunOffline.exe install -n Salome \
   -f C:/path/to/salome.tar.gz \
   -d C:\directory\you\want\to\keep\salome
```
and then I got an error see attached file.
[salome.log](https://github.com/DDoSolitary/LxRunOffline/files/1883302/salome.log)

**Comment by Trophime** [comment] 2018-04-06 08:58
One more note: in the gzipped tarball 
```
ar ztvf salome-8.4.0-nvidia.tar.gz | grep "opt/salome/Salome-V8_4_0-univ/modules/ADAO_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT"
drwxr-xr-x 71289/70017       0 2018-02-26 19:47 opt/salome/Salome-V8_4_0-univ/modules/ADAO_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT/
-rw-r--r-- 71289/70017     242 2018-02-26 19:08 opt/salome/Salome-V8_4_0-univ/modules/ADAO_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT/__init__.py
drwxr-xr-x 71289/70017       0 2018-02-26 19:47 opt/salome/Salome-V8_4_0-univ/modules/ADAO_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT__POA/
-rw-r--r-- 71289/70017     252 2018-02-26 19:08 opt/salome/Salome-V8_4_0-univ/modules/ADAO_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT__POA/__init__.py
-rw-r--r-- 71289/70017    4062 2018-03-19 13:27 opt/salome/Salome-V8_4_0-univ/modules/ADAO_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT_idl.py
lrwxrwxrwx 0/0                 0 2018-03-19 13:26 opt/salome/appli_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT -> /opt/salome/Salome-V8_4_0-univ/modules/ADAO_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT
lrwxrwxrwx 0/0                 0 2018-03-19 13:26 opt/salome/appli_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT__POA -> /opt/salome/Salome-V8_4_0-univ/modules/ADAO_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT__POA
lrwxrwxrwx 0/0                 0 2018-03-19 13:26 opt/salome/appli_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT_idl.py -> /opt/salome/Salome-V8_4_0-univ/modules/ADAO_V8_4_0/lib/python2.7/site-packages/salome/ADAO_COMPONENT_idl.py
```

**Comment by Trophime** [comment] 2018-04-06 09:03
@DDoSolitary seems like the error message concerns a soft link...
Could you please tell me what is the best way to "transform" a docker image into a Lxc image for WSL?

**Comment by DDoSolitary** [comment] 2018-04-06 10:03
I don't think this error was caused by the symlink because the file couldn't be created is the link target rather than the link itself.

**Comment by DDoSolitary** [comment] 2018-04-06 10:05
And in theory the tar.gz file is supported by LxRunOffline so it doesn't require any conversion.

**Comment by DDoSolitary** [comment] 2018-04-06 10:13
I don't think this error was caused by the symlink because it is the link target rahter than the link itself that could't be created.

**Comment by Trophime** [comment] 2018-04-06 11:13
no need to compress it one way or the other?
What is exactly the difference between `docker export` and `docker save`?

**Comment by DDoSolitary** [comment] 2018-07-06 12:01
Fixed in v3.
#36

**Closed by DDoSolitary** 2018-07-06 12:01 UTC
