### ISSUE TITLE
‘The parameter is incorrect’ after moving existing installation, even for new installations

### ISSUE THREAD

**Issue by Aankhen** [DDoSolitary/LxRunOffline#106] opened 2019-12-25 11:52 UTC
(Windows 10 Pro 64-bit version 1909, build 18363.476.)

I had (only) Ubuntu 18.04 installed through the Windows Store. I used `LxRunOffline m -n Ubuntu-18.04 -d D:\VMs\ubuntu` to move it. Now I just get ‘The parameter is incorrect’ when I try to run it:

```text
λ C:\Dev\LxRunOffline\LxRunOffline.exe r -n Ubuntu-18.04 echo hello
The parameter is incorrect.
```

I tried installing another copy of it to see if that would solve the problem, but it had the same result:

```text
λ curl -sLo C:\Temp\Dev\ubuntu-bionic-core-cloudimg-amd64-root.tar.gz https://lxrunoffline.apphb.com/ubuntu/bionic

λ LxRunOffline i -n Ubuntu-18.04-2 -d D:\VMs\ubuntu-2 -f C:\Temp\Dev\ubuntu-bionic-core-cloudimg-amd64-root.tar.gz
[WARNING] Love this tool? Would you like to make a donation: https://github.com/DDoSolitary/LxRunOffline/blob/master/README.md#donation

λ LxRunOffline r -n Ubuntu-18.04-2 echo hello
The parameter is incorrect.
```

And changing the distro didn’t help either:

```text
λ curl -sLo C:\Temp\Dev\debian.tar.gz https://lxrunoffline.apphb.com/download/debian/sid

λ LxRunOffline i -n Debian -d D:\VMs\debian -f C:\Temp\Dev\debian.tar.gz
[WARNING] Love this tool? Would you like to make a donation: https://github.com/DDoSolitary/LxRunOffline/blob/master/README.md#donation

λ LxRunOffline r -n Debian echo hello
The parameter is incorrect.
```

**Comment by DDoSolitary** [comment] 2019-12-25 21:49
Does the D: drive that you are moving to have anything special? For example, is it on a SD card or a storage space?

**Comment by Aankhen** [comment] 2019-12-26 09:37
No, it’s a regular hard disk.

**Comment by DDoSolitary** [comment] 2019-12-26 10:06
Could you please [capture the logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs) and either email them to me or post them here so that I can do more investigation?

**Comment by Aankhen** [comment] 2019-12-26 10:21
Sure, I can do that. For which part should I capture the logs? The whole thing from installation to execution?

**Comment by DDoSolitary** [comment] 2019-12-26 10:22
I think the execution part is enough.

**Comment by Aankhen** [comment] 2019-12-27 07:15
E-mailed them to you.

**Comment by Konfekt** [comment] 2020-01-01 19:05
The same error message over here by `wsl -d` and `lxrunoffline run`. In this case the distribution resides on a USB stick.

**Comment by DDoSolitary** [comment] 2020-01-01 19:26
Unfortunately, the log files didn't provide much useful information, except that the error originates from `lxssiptables.cpp`. If the distro installed from Windows Store worked before you moved it, could you please try a few more things?

- Does it work if you install another distro from Store
- Does it work if you install a distro using LxRunOffline into C: instead if D:

Thanks.

**Comment by DDoSolitary** [comment] 2020-01-01 20:28
@Konfekt Could you please provide your log files, too? Thanks.

**Comment by Konfekt** [comment] 2020-01-02 08:50
Regarding 

> Does it work if you install another distro from Store

the distribution it fails for over here is OpenSUSE-Leap-15-1.

**Comment by Aankhen** [comment] 2020-01-02 09:02
> Unfortunately, the log files didn't provide much useful information, except that the error originates from `lxssiptables.cpp`. If the distro installed from Windows Store worked before you moved it, could you please try a few more things?
> 
> * Does it work if you install another distro from Store

Yes, installing Kali Linux from the Store and running it works. For any of the distributions I interacted with LxRunOffline (by moving them or installing them), installing them from the Store works but running them fails, even after using LRO to uninstall them.

> * Does it work if you install a distro using LxRunOffline into C: (e.g. your user directory) instead of D:

Yes, installing Alpine Linux into a random directory under C: and running it via LRO works.

**Comment by DDoSolitary** [comment] 2020-01-02 18:00
As the distros installed to C: work no matter installed by Store or LxRunOffline, I think the errors are caused your hard drive rather than LxRunOffline. And unfortunately, I currently have no idea how to fix this. FWIW, an easy workaround would be using a virtual disk (e.g. VHDX, which is natively supported by Windows).

**Comment by YenLegion** [comment] 2020-02-13 16:22
I am having the same issue, except moving the directory back with lxrunoffline is now giving me the same error.

**Comment by DDoSolitary** [comment] 2020-06-18 05:36
I have to close this issue because I'm unable to reproduce it. Leave a comment if you find some new information that may help debugging.

**Closed by DDoSolitary** 2020-06-18 05:36 UTC
