### ISSUE TITLE
Default userid is ignored

### ISSUE THREAD

**Issue by Mystery0us** [DDoSolitary/LxRunOffline#28] opened 2018-02-23 13:01 UTC
> PS C:\Users\mystery\Downloads\LxRunOffline> .\LxRunOffline.exe config-uid -n ArchLinux
> [WARNING] You are running LxRunOffline with administrator privileges. It may cause problems.
> Do you want to continue? (y/n): y
> 1000
> PS C:\Users\mystery\Downloads\LxRunOffline> bash
> [root@DESKTOP-CHU61QE LxRunOffline]# id
> uid=0(root) gid=0(root) groups=0(root)
> [root@DESKTOP-CHU61QE LxRunOffline]# su mystery
> [mystery@DESKTOP-CHU61QE LxRunOffline]$ id
> uid=1000(mystery) gid=1000(mystery) groups=1000(mystery)
> [mystery@DESKTOP-CHU61QE LxRunOffline]$

I'm using LxRunOffline 2.2.2. The same thing happens when launching bash or wsl directly or using a non-admin poweshell

**Comment by DDoSolitary** [comment] 2018-02-24 04:14
I couldn't reproduce it on my machine. Please post the output of `reg query HKCU\Software\Microsoft\Windows\Lxss /s` so that I can diagnose the problem. Thanks.

**Comment by DDoSolitary** [comment] 2018-03-13 09:53
Closing as no response.

**Comment by sukhmel** [comment] 2018-06-05 21:01
I get the same problem: default UID (1000) is ignored. I tried running your command, and here is the output:
```
PS C:\> reg query HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss /s

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss
    DefaultDistribution    REG_SZ    {19f44f69-5afa-43c4-baf5-e88349148f67}

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{19f44f69-5afa-43c4-baf5-e88349148f67}
    DistributionName    REG_SZ    Ubuntu
    State    REG_DWORD    0x1
    Version    REG_DWORD    0x1
    BasePath    REG_SZ    c:\tools\lxss
    DefaultUid    REG_DWORD    0x3e8
```

**Comment by sukhmel** [comment] 2018-06-06 12:32
Seems to be more of a Windows problem:

1. After reboot bash no longer started, stating there are no distros installed. When I ran LxRunOffline:
    
    ```
    > LxRunOffline.exe run -n Ubuntu
    [ERROR] Win32 API returned an error: 0x800703FA.
    ```

2. I ran `LxRunOffline.exe default -n Ubuntu` again
3. Now default user is not ignored anymore

Registry values were all the same before and after I ran LxRunOffline.

**Comment by DDoSolitary** [comment] 2018-07-06 13:08
Maybe related: Microsoft/WSL#2576.
Please try restarting the LxssManager service.

**Comment by DDoSolitary** [comment] 2018-07-28 04:33
Closing as it seems to be Windows' fault.

**Closed by DDoSolitary** 2018-07-28 04:33 UTC
