### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by secure-code** [DDoSolitary/LxRunOffline#2] opened 2017-04-09 23:13 UTC
Hey, I built your program to .exe and ran on a Win10 VM. It asks for the paths of the image and icon file. After entering those it just closes the command prompt without any error. Somethings pops up in the command prompt screen but it closes quickly. No other errors and bash didn't get installed.

Can you please help how to make it work properly?

**Comment by DDoSolitary** [comment] 2017-04-09 23:46
@secure-code Sorry, the changes I made recently haven't been tested because I don't want to uninstall the BashOnWindows I already installed on my PC. I'll take a look now.

**Comment by DDoSolitary** [comment] 2017-04-09 23:50
@secure-code By the way, I noticed that you pinned this repo to your profile, but AFAIK, this can't be done before you contribute code to this repo. I asked the GitHub team but they had no ideas, too. I'm just a little curious, could you please talk about this?

**Comment by DDoSolitary** [comment] 2017-04-10 00:01
@secure-code I've confirmed this issue and am trying to fix now.

**Comment by DDoSolitary** [comment] 2017-04-10 00:14
@secure-code Did you just double-click the lxrunoffline.exe or run it using `lxrunoffline /install`? If you're doing as the former it is the expected behavior.

**Comment by secure-code** [comment] 2017-04-10 19:23
Hey, I don't know if I pinned it. I just pressed start button and now it shows in my starred items. Is there something you want me to undo with this?

**Comment by DDoSolitary** [comment] 2017-04-14 09:52
@secure-code Then it should be a bug on GitHub's side. Just ignore this. I believe that the GitHub team will deploy a fix soon.

**Comment by DDoSolitary** [comment] 2017-04-21 10:22
@secure-code I'm closing this as you said that you encountered the same issue in #1.

**Closed by DDoSolitary** 2017-04-21 10:22 UTC
