### ISSUE TITLE
Error while using CentOS docker image

### ISSUE THREAD

**Issue by eden881** [DDoSolitary/LxRunOffline#35] opened 2018-03-23 21:50 UTC
Hello,

I'm trying to use the official CentOS 7 docker image ([here](https://github.com/CentOS/sig-cloud-instance-images/blob/02904503939756f540cfaa3fbafbf280e8a11bef/docker/centos-7-docker.tar.xz)) as the installed distro.
When I try to install it I get:

`[ERROR] Couldn't open the file or directory "D:\LxRunOffline-v2.2.2\Installations\CentOS-7\rootfs\.\dev\".`

Is there something wrong with the docker image, or the way that LxRunOffline is trying to extract it? I think it should ignore the dot...

**Comment by Biswa96** [comment] 2018-03-24 18:06
The docker image works well if I convert the .tar.xz file to .tar.gz file. Maybe the problem lies in LxRunOffline.

**Comment by eden881** [comment] 2018-03-24 23:04
Can you please explain how do you perform the conversion?

**Comment by DDoSolitary** [comment] 2018-03-26 01:49
@eden881 It's no longer required to do so. The problem here is that you missed the `-r .` option when running LxRunOffline. (See [wiki](https://github.com/DDoSolitary/LxRunOffline/wiki))

**Comment by DDoSolitary** [comment] 2018-03-26 01:49
I'll try to do some automatic detection about the `.` directory.

**Comment by pilpoto** [comment] 2018-03-26 22:19
I have also a problem on CentOS7 installation :

LxRunOffline.exe install -n centOS-7 -r . -f centos-7-docker.tar.xz -d c:\centOS-7

[ERROR] Couldn't open the file or directory "C:\centOS-7\rootfs\var\lib\yum\yumdb\k\a9df4fc9aefe2a7f6533f931ad08a0f40813bcc8-krb5-libs-1.15.1-8.el7-x86_64\checksu".

I succeed in installing a Fedora27 but no centOS7 (I tried from .0 to .4). For each different release I got  an error such as the above one.

For 7.4 I got:
[ERROR] Couldn't create the hard link from "C:\centOS-7.4\rootfs\var\lib\yum\yumdb\u\c4f7c587789cecb3d3233c0ddd5039679febe6e0-util-linux-2.23.2-43.el7-x86_64\from_" to "C:\centOS-7.4\rootfs\var\lib\yum\yumdb\u\4d1fd565280360546ebe8f747fd64942ccc7b300-ustr-1.0.4-16.el7-x86_64\from_repo_re".

From 7.0 to 7.2 I got:
[ERROR] Couldn't open the file or directory "C:\centOS-7\rootfs\.\@LongLink".

**Comment by eden881** [comment] 2018-04-06 06:55
I can confirm that when I add `-r .` to the command, I have the same issue as @pilpoto (LxRunOffline 2.2.2, CentOS 7.4).

**Comment by DDoSolitary** [comment] 2018-04-06 07:57
This problem seems to be caused by the tar reader SharpZipLib, which I will replace with libarchive in v3.

**Comment by Voskrese** [comment] 2018-06-14 19:29
@DDoSolitary 
thanks for the utility, everything works fine and is installed
> спасибо за утилиту, все прекрасно работает и устанавливается

https://github.com/Voskrese/CentOSWSL

**Comment by DDoSolitary** [comment] 2018-07-06 12:36
Fixed in v3.

**Closed by DDoSolitary** 2018-07-06 12:36 UTC
